### ISSUE TITLE
Check if users are logged in before inserting raids

### ISSUE THREAD

**Issue by celsom3** [Cosecha/redadas-de-obama#21]
Along the lines of
```
if( !this.userId ) { 
    not logged in
}

```

**Comment by justrdk** [comment]
@celsom3 I'll tackle this over the weekend. I'll refactor the way meteor methods are being created and add validated schema to them. 

thinking about instead of using Meteor.methods({}) export each method and import them from the ui wherever we need them.

something like
`` export const insert = new ValidatedMethod(etc)``
instead of 
``Meteor.methods({insert(data) { //logic here })``
